//actions
export const FETCH_REPOSITORY_STATUS = "FETCH_REPOSITORY_STATUS";
export const FETCH_FILE_CHANGES = "FETCH_FILE_CHANGES";
//
export const STAGE_FILE = "STAGE_FILE";
export const UNSTAGE_FILE = "UNSTAGE_FILE";

//mutations
export const APPLY_REPOSITORY_STATUS = "APPLY_REPOSITORY_STATUS"

//commitArea types
//mutations
export const CLEAR_SELECTED_COMMIT = "CLEAR_SELECTED_COMMIT";
export const GET_COMMIT_TREE_FROM_TIP = "GET_COMMIT_TREE_FROM_TIP";
export const GET_COMMIT_TREE_FROM_HEAD = "GET_COMMIT_TREE_FROM_HEAD";

//branchArea
export const GET_ALL_BRANCHES = "GET_ALL_BRANCHES";
export const CREATE_NEW_BRANCH = "CREATE_NEW_BRANCH";
export const CHECKOUT_BRANCH = "CHECKOUT_BRANCH";


export const COMMIT = "COMMIT";

export const DISCARD_ALL_CHANGES = "DISCARD_ALL_CHANGES";

export const DISCARD_FILE_CHANGES = "DISCARD_FILE_CHANGES";
