//mutations
export const FETCH_UNSTAGED_FILES = "FETCH_UNSTAGED_FILES";
export const FETCH_STAGED_FILES = "FETCH_STAGED_FILES";
export const FETCH_FILE_CHANGES = "FETCH_FILE_CHANGES";
//
export const STAGE_FILE = "STAGE_FILE";
export const UNSTAGE_FILE = "UNSTAGE_FILE";

//mutations
export const APPLY_UNSTAGED_FILES = "APPLY_UNSTAGED_FILES"
export const APPLY_STAGED_FILES = "APPLY_STAGED_FILES"

//commitArea types
//mutations
export const CLEAR_SELECTED_COMMIT = "CLEAR_SELECTED_COMMIT";
